# Generated by Django 3.2.16 on 2023-01-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
