# Generated by Django 3.2.16 on 2023-01-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='about',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
