# Generated by Django 3.2.16 on 2023-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20230117_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
