# Generated by Django 3.2.16 on 2023-01-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_boxes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boxes',
            new_name='Box',
        ),
    ]
