# Generated by Django 3.2.16 on 2023-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_boxes_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
