# Generated by Django 3.2.16 on 2023-01-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_box_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='slug',
        ),
    ]
