# Generated by Django 3.2.16 on 2023-01-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_box_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box',
        ),
    ]
